name:                aeson-typescript
version:             0.1.1.0
github:              "codedownio/aeson-typescript"
license:             BSD3
category:            Text, Web, JSON
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2018 CodeDown"

extra-source-files:
- README.md
- ChangeLog.md
- test/assets/package.json
- test/assets/npm_install.sh
- test/assets/yarn_install.sh
- test/assets/yarn.lock

# Metadata used when publishing your package
synopsis:            Generate TypeScript definition files from your ADTs

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/codedownio/aeson-typescript#readme>

tested-with: GHC == 7.6.3, GHC == 7.8.4, GHC == 7.10.2

dependencies:
- aeson
- base >= 4.7 && < 5
- containers
- interpolate
- mtl
- template-haskell
- text
- th-abstraction
- unordered-containers

library:
  source-dirs: src
  exposed-modules: [Data.Aeson.TypeScript.TH, Data.Aeson.TypeScript.Types]

tests:
  aeson-typescript-test:
    main:                Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson-typescript
    - bytestring
    - directory
    - filepath
    - hspec
    - process
    - temporary
